### ISSUE TITLE
Restoring the checkpoint kept on failing. Please help me out...

### ISSUE THREAD

**Issue by sahaypushkar** [HyeongseokSon1/deep_blur_detection_and_classification#6]
Working Environment:
Tensorflow= 1.14.0
Tensorlayer= 1.8.2
Python 3.7

2019-12-26 13:12:01.314438: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key Unified/UNet/u1/d/W_deconv2d not found in checkpoint
Traceback (most recent call last):
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key Unified/UNet/u1/d/W_deconv2d not found in checkpoint
	 [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1286, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key Unified/UNet/u1/d/W_deconv2d not found in checkpoint
	 [[node save/RestoreV2 (defined at main.py:103) ]]

Original stack trace for 'save/RestoreV2':
  File "main.py", line 157, in <module>
    blurmap_3classes(args.index) # test_code
  File "main.py", line 103, in blurmap_3classes
    saver = tf.compat.v1.train.Saver()
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 825, in __init__
    self.build()
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 837, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 875, in _build
    build_restore=build_restore)
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1296, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1614, in object_graph_key_mapping
    object_graph_string = reader.get_tensor(trackable.OBJECT_GRAPH_PROTO_KEY)
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 678, in get_tensor
    return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str))
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 157, in <module>
    blurmap_3classes(args.index) # test_code
  File "main.py", line 108, in blurmap_3classes
    saver.restore(sess, "./model/final_model.ckpt")
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1302, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key Unified/UNet/u1/d/W_deconv2d not found in checkpoint
	 [[node save/RestoreV2 (defined at main.py:103) ]]

Original stack trace for 'save/RestoreV2':
  File "main.py", line 157, in <module>
    blurmap_3classes(args.index) # test_code
  File "main.py", line 103, in blurmap_3classes
    saver = tf.compat.v1.train.Saver()
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 825, in __init__
    self.build()
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 837, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 875, in _build
    build_restore=build_restore)
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/home/kylo/Downloads/MotionBlur-detection-by-CNN-master/venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by HyeongseokSon1** [comment]
Sorry, we could not identify the reason.
Please test with lower versions of Tensoflow.
